version: 2.1
executors:
  publisher:
    environment:
      IMAGE_NAME: cloudokihub/appdoki-be
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  build:
    executor: publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker push $IMAGE_NAME
  deploy:
    machine: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "fb:0a:f3:01:af:80:61:20:08:60:93:db:de:70:9d:47"
      - run:
          name: Deploy Over SSH
          command: |
            scp -r -o StrictHostKeyChecking=no docker-compose.yml $SSH_USER@$SSH_HOST:~/appdoki/
            ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "cd appdoki && docker-compose pull && source .env && docker-compose up -d --force-recreate"

workflows:
  version: 2
  build_deploy:
    jobs:
      - build:
          context: cloudoki-docker
          filters:
            branches:
              only:
                - main
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - build